# -*- coding: utf-8 -*-
"""audio_to_midi_arrangement_assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rKcdrTASpZrVDmP0aXaQV5uTjV6g-0ks

# 🎧 AI Audio-to-MIDI Transcriptor
Pipeline completa: separazione stem (Demucs) → analisi musicale (BPM/tonalità/accordi) → trascrizione audio-to-MIDI (basic-pitch).

**Come usarlo:**
1. Esegui le celle in ordine (Runtime → Run all, oppure una per una).
2. Nella cella "Step 1" carica un file audio (.wav/.mp3).
3. Alla fine trovi il file `.mid` scaricabile.

Consiglio: su Colab attiva una GPU (Runtime → Change runtime type → GPU) per velocizzare Demucs.

## Setup — installazione dipendenze
"""

# torch/torchaudio dovrebbero essere già presenti su Colab

!pip install -q pretty_midi
!pip install -q demucs

print("Installazione completata.")

import os
import json
import subprocess
from pathlib import Path

import numpy as np
import librosa
import pretty_midi
from IPython.display import Audio, display

from google.colab import files

"""## Step 1 — Carica il file audio

Eseguendo la cella si aprirà un selettore file. Carica una traccia .wav o .mp3.
"""

uploaded = files.upload()
input_filename = list(uploaded.keys())[0]
input_path = f"/content/{input_filename}"
print(f"File caricato: {input_path}")

display(Audio(input_path))

"""## Step 2 — Separazione degli stem (Demucs)

Separa il brano in `drums`, `bass`, `vocals`, `other`. Su Colab con GPU ci vogliono circa 120/180 secondi per brano se caricato in formato .wav
"""

def separate_stems(audio_path: str, output_dir: str = "/content/separated", model: str = "htdemucs"):
    subprocess.run(
        ["demucs", "-n", model, "-o", output_dir, audio_path],
        check=True
    )
    stem_name = Path(audio_path).stem
    stem_dir = Path(output_dir) / model / stem_name
    stems = {f.stem: str(f) for f in stem_dir.glob("*.wav")}
    return stems

stems = separate_stems(input_path)
print("Stem generati:")
for name, path in stems.items():
    print(f" - {name}: {path}")

# Ascolta rapidamente ogni stem separato
for name, path in stems.items():
    print(f"--- {name} ---")
    display(Audio(path))

"""## Step 3 — Analisi musicale: BPM, tonalità, accordi

Lavoriamo sul mix originale per BPM/tonalità (più stabile), e sugli stem separati per la trascrizione MIDI (Step 4).
"""

y, sr = librosa.load(input_path, sr=None)

# --- BPM ---
tempo, beat_frames = librosa.beat.beat_track(y=y, sr=sr)
bpm = float(np.atleast_1d(tempo)[0])
print(f"BPM stimato: {bpm:.1f}")

# --- Tonalità (Krumhansl-Schmuckler) ---
chroma = librosa.feature.chroma_cqt(y=y, sr=sr)
chroma_mean = chroma.mean(axis=1)

NOTE_NAMES = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"]

major_profile = np.array([6.35,2.23,3.48,2.33,4.38,4.09,2.52,5.19,2.39,3.66,2.29,2.88])
minor_profile = np.array([6.33,2.68,3.52,5.38,2.60,3.53,2.54,4.75,3.98,2.69,3.34,3.17])

def estimate_key(chroma_vec):
    best_score, best_key = -1, None
    for i in range(12):
        maj_corr = np.corrcoef(np.roll(major_profile, i), chroma_vec)[0, 1]
        min_corr = np.corrcoef(np.roll(minor_profile, i), chroma_vec)[0, 1]
        if maj_corr > best_score:
            best_score, best_key = maj_corr, f"{NOTE_NAMES[i]} major"
        if min_corr > best_score:
            best_score, best_key = min_corr, f"{NOTE_NAMES[i]} minor"
    return best_key

key = estimate_key(chroma_mean)
print(f"Tonalità stimata: {key}")

# --- Accordi (stima per segmento via template-matching sui chroma) ---
# Approccio leggero pensato per Colab (evita dipendenze pesanti come madmom).
# Per ogni battito, prendiamo il chroma medio e lo confrontiamo con 24 template (12 maj + 12 min).

def build_chord_templates():
    templates = {}
    for i, note in enumerate(NOTE_NAMES):
        maj = np.zeros(12); maj[[i, (i+4) % 12, (i+7) % 12]] = 1
        minr = np.zeros(12); minr[[i, (i+3) % 12, (i+7) % 12]] = 1
        templates[f"{note}"] = maj
        templates[f"{note}m"] = minr
    return templates

templates = build_chord_templates()

def estimate_chords_per_beat(chroma, beat_frames):
    chords = []
    for i in range(len(beat_frames) - 1):
        start, end = beat_frames[i], beat_frames[i+1]
        if end <= start:
            continue
        seg_chroma = chroma[:, start:end].mean(axis=1)
        best_chord, best_score = None, -1
        for name, template in templates.items():
            score = np.dot(seg_chroma, template) / (np.linalg.norm(seg_chroma) * np.linalg.norm(template) + 1e-8)
            if score > best_score:
                best_score, best_chord = score, name
        chords.append(best_chord)
    return chords

chord_sequence = estimate_chords_per_beat(chroma, beat_frames)

# Comprimi ripetizioni consecutive per leggibilità
compact_chords = []
for c in chord_sequence:
    if not compact_chords or compact_chords[-1] != c:
        compact_chords.append(c)

print("Sequenza accordi (compattata):", compact_chords)

# --- Struttura del brano (segmentazione approssimativa) ---
S = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=13)
bounds = librosa.segment.agglomerative(S, k=6)  # 6 segmenti approssimativi
bound_times = librosa.frames_to_time(bounds, sr=sr)
print("Confini di sezione stimati (secondi):", np.round(bound_times, 1).tolist())

features = {
    "bpm": round(bpm, 1),
    "key": key,
    "chords": compact_chords[:16],  # limitiamo per non appesantire il prompt LLM
    "structure_boundaries_sec": np.round(bound_times, 1).tolist(),
    "stems_present": list(stems.keys())
}
print(json.dumps(features, indent=2))

"""## Step 4 — Trascrizione Audio-to-MIDI (basic-pitch)

Trascriviamo ogni stem separatamente: basic-pitch lavora molto meglio su sorgenti isolate che sul mix completo.
"""

from basic_pitch.inference import predict
from basic_pitch import ICASSP_2022_MODEL_PATH

midi_dir = Path("/content/midi_transcriptions")
midi_dir.mkdir(exist_ok=True)

transcribed_midi_paths = {}

for stem_name, stem_path in stems.items():
    if stem_name == "drums":
        # basic-pitch è pensato per contenuto armonico/melodico, non per batteria
        continue
    print(f"Trascrivo: {stem_name}...")
    model_output, midi_data, note_events = predict(stem_path, ICASSP_2022_MODEL_PATH)
    out_path = midi_dir / f"{stem_name}.mid"
    midi_data.write(str(out_path))
    transcribed_midi_paths[stem_name] = str(out_path)
    print(f" -> salvato in {out_path}")

print("\nTrascrizione completata:", transcribed_midi_paths)

files.download(out_path)